site_name: General Inquirer

theme:
  name: 'material'
  custom_dir: 'theme'
  font:
    text: 'IBM Plex'
    code: 'IBM Plex Mono'
  palette:
    primary: 'blue grey'
    accent: 'blue'
  logo:
    icon: 'import_contacts'

markdown_extensions:
  - codehilite

repo_name: 'pmbaumgarnter/general-inquirer-remix'
repo_url: 'https://github.com/pmbaumgartner/general-inquirer-remix'
